### ISSUE TITLE
Analysand::Http::_req does not escape document IDs clearly

### ISSUE THREAD

**Issue by anarchivist** [yipdw/analysand#7]
I'm running into an issue where a partner's database has keys that look like `10067--http://ark.cdlib.org/ark:/13030/kt067nc38g`. The docs for `Analysand::Database` note the following:

```
  # Note: CouchDB treats forward slashes (/) specially.  For document IDs, /
  # denotes a separator between document ID and the name of an attachment.
  # This library makes use of that to implement attachment storage and
  # retrieval (see below).
  #
  # If you are using forward slashes in document IDs, you MUST encode them
  # (i.e. replace / with %2F).
```

In my case, I've made sure that I've escaped the IDs (using `CGI.escape`), before they even get passed to `Analysand::Http::_req`. This ensures an ID like `10067--http%3A%2F%2Fark.cdlib.org%2Fark%3A%2F13030%2Fkt067nc38g` gets passed to `Analysand::Http::_req`.

However, given that `%` is a reserved character in URIs, it gets escaped _again_ (when `Analysand::Http::_req` calls `URI.escape`, which means the actual document ID that gets requested is `10067--http%253A%252F%252Fark.cdlib.org%252Fark%253A%252F13030%252Fkt067nc38g`. (In other words, the `%` characters get double-escaped.)

**Comment by yipdw** [comment]
Yep, this definitely looks like an error in the library.  There's some examples that rely on this too, e.g. all the "escapes document IDs" examples.

Given that `URI.escape` is not idempotent, I wonder if the simplest solution is to remove that from `_req` and place that responsibility on the library user (which the docs already imply, anyway).

**Comment by anarchivist** [comment]
That sounds reasonable to me. :+1:

**Comment by yipdw** [comment]
Cool. :) I can prepare a patch later today; will probably also release as version 4.0.0.

**Comment by yipdw** [comment]
Hi! Sorry for the delay: 

1) life stuff
2) it turns out that not escaping document IDs is a bit more subtle than I thought

In particular, COPY-with-document-ID seems to expect the destination ID to be _un_escaped.  (Not sure what happens in the COPY-with-URI-as-destination form.)  I was attempting to find official confirmation of this in the CouchDB API docs, but couldn't locate that.  Ah well.

Anyway, c27a7632e23b4757a0d98da6d74ac4aff4ab1fc9 contains the proposed fix and bumps the version to 4.0.0.pre.  Let me know how this works out for you; if it fixes the escaping problem, I'll go ahead and do 3.1.0 / 4.0.0 releases.

**Comment by anarchivist** [comment]
Great - looks like that works for me. Thanks again!

**Comment by yipdw** [comment]
Cool, good to hear!

I've done a release of 4.0.0 from c7629fd3275fc27b9d4b29137038ee0b60e64c16 (tag v4.0.0).
